interface Datum {
    text: string;
    value: number;
}

export const wordsEn: Datum[] = [
    {
        text: 'HAJIUNG',
        value: 5000,
    },
    { text: 'banana', value: 23 },
    { text: 'elephant', value: 65 },
    { text: 'computer', value: 40 },
    { text: 'chocolate', value: 12 },
    { text: 'library', value: 14 },
    { text: 'butterfly', value: 37 },
    { text: 'guitar', value: 53 },
    { text: 'umbrella', value: 47 },
    { text: 'restaurant', value: 54 },
    { text: 'mountain', value: 56 },
    { text: 'sunshine', value: 9 },
    { text: 'pineapple', value: 52 },
    { text: 'kangaroo', value: 29 },
    { text: 'strawberry', value: 33 },
    { text: 'astronaut', value: 35 },
    { text: 'waterfall', value: 8 },
    { text: 'rainbow', value: 62 },
    { text: 'bicycle', value: 21 },
    { text: 'television', value: 41 },
    { text: 'spaceship', value: 68 },
    { text: 'React', value: 30 },
    { text: 'Vue', value: 16 },
    { text: 'Angular', value: 22 },
    { text: 'JavaScript', value: 7 },
    { text: 'TypeScript', value: 19 },
    { text: 'CSS', value: 23 },
    { text: 'HTML', value: 25 },
    { text: 'Webpack', value: 14 },
    { text: 'Babel', value: 10 },
    { text: 'Sass', value: 12 },
    { text: 'Bootstrap', value: 9 },
    { text: 'Material UI', value: 21 },
    { text: 'Styled Components', value: 11 },
    { text: 'Redux', value: 17 },
    { text: 'MobX', value: 8 },
    { text: 'GraphQL', value: 18 },
    { text: 'REST API', value: 29 },
    { text: 'Axios', value: 30 },
    { text: 'Jest', value: 10 },
    { text: 'Cypress', value: 12 },
    { text: 'Next.js', value: 28 },
    { text: 'Gatsby', value: 29 },
    { text: 'Nuxt.js', value: 11 },
    { text: 'Webpack Dev Server', value: 26 },
    { text: 'ESLint', value: 12 },
    { text: 'Prettier', value: 22 },
    { text: 'Visual Studio Code', value: 7 },
    { text: 'CodeSandbox', value: 12 },
    { text: 'GitHub', value: 28 },
    { text: 'Netlify', value: 7 },
    { text: 'Vercel', value: 19 },
    { text: 'Firebase', value: 19 },
    { text: 'AWS Amplify', value: 18 },
    { text: 'Google Cloud', value: 8 },
    { text: 'Cloudinary', value: 12 },
    { text: 'Docker', value: 11 },
    { text: 'Kubernetes', value: 21 },
    { text: 'Netlify CMS', value: 21 },
    { text: 'Strapi', value: 21 },
    { text: 'React Native', value: 16 },
    { text: 'Node.js', value: 27 },
    { text: 'GraphQL', value: 22 },
    { text: 'Next.js', value: 28 },
    { text: 'React', value: 30 },
    { text: 'Responsive design', value: 14 },
    { text: 'Redux', value: 8 },
    { text: 'TypeScript', value: 17 },
    { text: 'SEO', value: 12 },
    { text: 'Unit testing', value: 15 },
    { text: 'WebGL', value: 19 },
    { text: 'Tailwind CSS', value: 8 },
    { text: 'Angular', value: 26 },
    { text: 'Material-UI', value: 6 },
    { text: 'CSS', value: 25 },
    { text: 'Storybook', value: 12 },
    { text: 'D3.js', value: 29 },
    { text: 'PWA', value: 12 },
    { text: 'Three.js', value: 25 },
    { text: 'SPA', value: 23 },
    { text: 'Accessibility', value: 8 },
    { text: 'Bootstrap', value: 29 },
    { text: 'Node.js', value: 29 },
    { text: 'Cypress', value: 9 },
    { text: 'End-to-end testing', value: 29 },
    { text: 'Integration testing', value: 7 },
    { text: 'HTML', value: 10 },
    { text: 'MobX', value: 7 },
    { text: 'Webpack', value: 9 },
    { text: 'Sass', value: 6 },
    { text: 'RxJS', value: 27 }
];

export const loadingWords = [
    {
        text: '치킨',
        key: 5
    },
    {
        text: '피자',
        key: 4
    },
    {
        text: '햄버거',
        key: 3
    },
    {
        text: '곱창',
        key: 2
    },
    {
        text: '삼겹살',
        key: 1
    },
]